
//----------------------------------------------------
// The following code was generated by CUP v0.11b 20160615 (GIT 4ac7450)
//----------------------------------------------------

package codigo;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int Values = 21;
  public static final int Palabra_clave = 6;
  public static final int Numero = 2;
  public static final int Delete = 12;
  public static final int Update = 13;
  public static final int Identificador = 5;
  public static final int P_coma = 20;
  public static final int Asterisco = 18;
  public static final int Operador = 10;
  public static final int Cadena = 7;
  public static final int Select = 11;
  public static final int EOF = 0;
  public static final int Delimitador = 3;
  public static final int Where = 17;
  public static final int Linea = 4;
  public static final int error = 1;
  public static final int Igual = 19;
  public static final int Parentesis = 8;
  public static final int Set = 15;
  public static final int From = 16;
  public static final int Error = 9;
  public static final int Insert = 14;
  public static final String[] terminalNames = new String[] {
  "EOF",
  "error",
  "Numero",
  "Delimitador",
  "Linea",
  "Identificador",
  "Palabra_clave",
  "Cadena",
  "Parentesis",
  "Error",
  "Operador",
  "Select",
  "Delete",
  "Update",
  "Insert",
  "Set",
  "From",
  "Where",
  "Asterisco",
  "Igual",
  "P_coma",
  "Values"
  };
}

